defaults:
  - base_dataset
_target_: calo_cluster.datasets.semantic_kitti_offset.SemanticKITTIOffsetDataModule

# required fields:
num_classes: 19
num_features: 4
voxel_size: 0.05

# dataset-specific fields (should not change):
valid_labels: [0, 1, 2, 3, 4, 5, 6, 7]
semantic_ignore_label: 255

# data location (modify as needed):
root: /data/semantic_kitti/dataset/sequences

# config fields:
num_points: 80000