defaults:
  - base_dataset
_target_: calo_cluster.datasets.simple.SimpleDataModule

# required fields:
num_classes: 2
num_features: 4
voxel_size: 0.05

# dataset-specific fields (should not change):
cluster_ignore_label: 0

# data location (modify as needed):
data_dir: /content/drive/MyDrive/ML-Vertexing/data/simple/ # Google Colab path

# config fields:
feats: ['x', 'y', 'z', 'E']
coords: ['x', 'y', 'z']